### ISSUE TITLE
RGBからステータスの生成する

### ISSUE THREAD

**Issue by woods-one** [Conken-NitKit/Hackz_Hackathon_Pteracup#4]

**Comment by TakayamaH** [comment]
@woods-one 
今書いてるんですけど、以下の2点だけ確認したいです なんかあれば教えてください
1. RGBは渡されるときstring型("#FFA500")？Color32？
2. 「特殊技みたいなのを確定で1つだけ持たせる」っていうのの編成は？
    - 特殊技は16種類
        - 特殊技1つ + 通常技3つのセットをRの一の桁で指定
        - ランダムな特殊技1つ + Rの一の桁で指定した指定した通常技3つ
        - Rの一の桁で指定した特殊技1つ + ランダムな通常技3つ
    - 特殊技は1個だけ
        - めざめるパワー的なやつ
    
忙しいとは思いますがよろしくお願いします～

**Comment by woods-one** [comment]
1.stringです。
2.特殊技は16種類で考えてました。  
あと、Rの一の桁で指定するのは特殊技だけで、通常技(攻撃)は全キャラクター共通で一つだけあるものとするつもりです。

想定としては、
- 攻撃(攻撃力分をそのまま、あるいはちょっと上下させるかも、与える)
- 特殊技(回復だったり倍率ダメージだったり)
- 防御(1ターンだけ防御力アップ)  
みたいに3つコマンドがあるのを想定してます。

**Comment by TakayamaH** [comment]
回答ありがとうございます！
だいぶ考えていたのと違ったので確認出来て良かったです～ありがとう！
